INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO users (name, age) VALUES ("Sanj", 30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xbox", "Gaming", 1000, "May 2, 2021", "June 2, 2021");
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);